import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import { ContextProviders } from '@/contexts';

// eslint-disable-next-line new-cap, quotes
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: `Create Next App`,
  description: `Generated by create next app`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ContextProviders>
      <html lang='en'>
        <body className={inter.className}>{children}</body>
      </html>
    </ContextProviders>
  );
}
